Repository MTVS-Sept-Collaboration/Back-End, pull requests merged in 2024-09, with the labels that each got.

#2 Feat: 카카오 로그인 및 회원가입 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/homefit/backend/BackendApplication.java
  src/main/java/com/homefit/backend/global/util/OpenApiConfig.java
  src/main/java/com/homefit/backend/login/common/ApiResponse.java
  src/main/java/com/homefit/backend/login/common/CookieUtil.java
  src/main/java/com/homefit/backend/login/common/HeaderUtil.java
  src/main/java/com/homefit/backend/login/config/properties/AppProperties.java
  src/main/java/com/homefit/backend/login/config/properties/CorsProperties.java
  src/main/java/com/homefit/backend/login/config/security/JwtConfig.java
  src/main/java/com/homefit/backend/login/config/security/SecurityConfig.java
  src/main/java/com/homefit/backend/login/controller/api/KakaoAuthController.java
  src/main/java/com/homefit/backend/login/dto/KakaoLoginRequest.java
  src/main/java/com/homefit/backend/login/dto/UserDto.java
  src/main/java/com/homefit/backend/login/entity/User.java
  src/main/java/com/homefit/backend/login/oauth/entity/ProviderType.java
  src/main/java/com/homefit/backend/login/oauth/entity/RoleType.java
  src/main/java/com/homefit/backend/login/oauth/entity/user/UserPrincipal.java
  src/main/java/com/homefit/backend/login/oauth/exception/RestAuthenticationEntryPoint.java
  src/main/java/com/homefit/backend/login/oauth/exception/TokenValidFailedException.java
  src/main/java/com/homefit/backend/login/oauth/filter/TokenAuthenticationFilter.java
  src/main/java/com/homefit/backend/login/oauth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/homefit/backend/login/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/homefit/backend/login/oauth/handler/TokenAccessDeniedHandler.java
  src/main/java/com/homefit/backend/login/oauth/info/OAuth2UserInfo.java
  src/main/java/com/homefit/backend/login/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/com/homefit/backend/login/oauth/info/impl/KakaoOAuth2UserInfo.java
  src/main/java/com/homefit/backend/login/oauth/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/homefit/backend/login/oauth/repository/UserRepository.java
  src/main/java/com/homefit/backend/login/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/homefit/backend/login/oauth/token/AuthToken.java
  src/main/java/com/homefit/backend/login/oauth/token/AuthTokenProvider.java
  src/main/java/com/homefit/backend/login/service/KakaoAuthService.java
Labels: ✨ Feature

#8 Chore: build.gradle 및 ApiResponse 클래스명 변경
  build.gradle
  src/main/java/com/homefit/backend/login/common/CustomApiResponse.java
Labels: 🔨 Refactor

#15 feat: #14- 아이템카테고리 crud 완료
  src/main/java/com/homefit/backend/Itemcategory/controller/ItemCategoryController.java
  src/main/java/com/homefit/backend/Itemcategory/dto/ItemCategoryRequest.java
  src/main/java/com/homefit/backend/Itemcategory/dto/ItemCategoryResponse.java
  src/main/java/com/homefit/backend/Itemcategory/entity/ItemCategory.java
  src/main/java/com/homefit/backend/Itemcategory/repository/ItemCategoryRepository.java
  src/main/java/com/homefit/backend/Itemcategory/service/ItemCategoryService.java
  src/main/java/com/homefit/backend/category/controller/CategoryController.java
  src/main/java/com/homefit/backend/category/dto/CategoryRequest.java
  src/main/java/com/homefit/backend/category/dto/CategoryResponse.java
  src/main/java/com/homefit/backend/category/repository/CategoryRepository.java
  src/main/java/com/homefit/backend/category/service/CategoryService.java
  src/test/java/com/homefit/backend/Category/service/CategoryServiceTest.java
  src/test/java/com/homefit/backend/itemCategory/service/ItemCategoryServiceTest.java
Labels: ✨ Feature

#19 feat: #16- 운동 카테고리 crud 완료
  src/main/java/com/homefit/backend/exerciseCategory/controller/ExerciseCategoryController.java
  src/main/java/com/homefit/backend/exerciseCategory/dto/ExerciseCategoryRequest.java
  src/main/java/com/homefit/backend/exerciseCategory/dto/ExerciseCategoryResponse.java
  src/main/java/com/homefit/backend/exerciseCategory/entity/ExerciseCategory.java
  src/main/java/com/homefit/backend/exerciseCategory/repository/ExerciseCategoryRepository.java
  src/main/java/com/homefit/backend/exerciseCategory/service/ExerciseCategoryService.java
  src/main/java/com/homefit/backend/login/config/security/SecurityConfig.java
  src/test/java/com/homefit/backend/exerciseCategory/service/ExerciseCategoryServiceTest.java
Labels: ✨ Feature

#21 Feat exercise
  src/main/java/com/homefit/backend/Itemcategory/entity/ItemCategory.java
  src/main/java/com/homefit/backend/exercise/controller/ExerciseController.java
  src/main/java/com/homefit/backend/exercise/dto/ExerciseRequest.java
  src/main/java/com/homefit/backend/exercise/dto/ExerciseResponse.java
  src/main/java/com/homefit/backend/exercise/entity/Exercise.java
  src/main/java/com/homefit/backend/exercise/repository/ExerciseRepository.java
  src/main/java/com/homefit/backend/exercise/service/ExerciseService.java
  src/main/java/com/homefit/backend/exerciseCategory/entity/ExerciseCategory.java
  src/main/java/com/homefit/backend/exerciseLog/controller/ExerciseLogController.java
  src/main/java/com/homefit/backend/exerciseLog/dto/ExerciseLogRequest.java
  src/main/java/com/homefit/backend/exerciseLog/dto/ExerciseLogResponse.java
  src/main/java/com/homefit/backend/exerciseLog/entity/ExerciseLog.java
  src/main/java/com/homefit/backend/exerciseLog/repository/ExerciseLogRepository.java
  src/main/java/com/homefit/backend/exerciseLog/service/ExerciseLogService.java
  src/test/java/com/homefit/backend/exercise/service/ExerciseServiceTest.java
  src/test/java/com/homefit/backend/exeriseLog/ExerciseLogServiceTest.java
Labels: ✨ Feature

#22 Feat: 유저 정보 BMI 계산 기능 구현
  src/main/java/com/homefit/backend/user/controller/UserInfoController.java
  src/main/java/com/homefit/backend/user/dto/UserInfoDto.java
  src/main/java/com/homefit/backend/user/entity/UserInfo.java
  src/main/java/com/homefit/backend/user/service/UserInfoService.java
Labels: ✨ Feature

#25 Feat/item
  src/main/java/com/homefit/backend/item/controller/ItemController.java
  src/main/java/com/homefit/backend/item/dto/ItemListResponseDto.java
  src/main/java/com/homefit/backend/item/dto/ItemModifyRequestDto.java
  src/main/java/com/homefit/backend/item/dto/ItemResponseDto.java
  src/main/java/com/homefit/backend/item/dto/ItemSaveRequestDto.java
  src/main/java/com/homefit/backend/item/entity/Item.java
  src/main/java/com/homefit/backend/item/repository/ItemRepository.java
  src/main/java/com/homefit/backend/item/service/ItemService.java
  src/main/java/com/homefit/backend/itemcategory/controller/ItemCategoryController.java
  src/main/java/com/homefit/backend/itemcategory/dto/ItemCategoryRequest.java
  src/main/java/com/homefit/backend/itemcategory/dto/ItemCategoryResponse.java
  src/main/java/com/homefit/backend/itemcategory/entity/ItemCategory.java
  src/main/java/com/homefit/backend/itemcategory/repository/ItemCategoryRepository.java
  src/main/java/com/homefit/backend/itemcategory/service/ItemCategoryService.java
  src/test/java/com/homefit/backend/item/repository/ItemRepositoryTest.java
  src/test/java/com/homefit/backend/itemCategory/service/ItemCategoryServiceTest.java
Labels: ✨ Feature, ✅ Test

#24 Refactor: 로그인 및 Swagger 문서 수정
  src/main/java/com/homefit/backend/global/util/OpenApiConfig.java
  src/main/java/com/homefit/backend/login/controller/api/KakaoAuthController.java
  src/main/java/com/homefit/backend/login/service/KakaoAuthService.java
  src/main/java/com/homefit/backend/user/controller/UserInfoController.java
  src/test/java/com/homefit/backend/login/LoginServiceTest.java
Labels: 📃 Docs, 🔨 Refactor

#33 Feat/item
  src/main/java/com/homefit/backend/item/controller/ItemController.java
  src/main/java/com/homefit/backend/item/repository/ItemRepository.java
  src/main/java/com/homefit/backend/item/service/ItemService.java
Labels: ✨ Feature

#38 Feat exercise
  .gitignore
  gradlew
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ⚙️ Setting

#40 [SETTING] 깃 충돌 이슈 해결
  src/main/java/com/homefit/backend/global/util/OpenApiConfig.java
  src/main/java/com/homefit/backend/login/common/CustomApiResponse.java
  src/main/java/com/homefit/backend/login/config/properties/AppProperties.java
  src/main/java/com/homefit/backend/login/config/properties/CorsProperties.java
  src/main/java/com/homefit/backend/login/config/security/SecurityConfig.java
  src/main/java/com/homefit/backend/login/controller/api/KakaoAuthController.java
  src/main/java/com/homefit/backend/login/entity/User.java
  src/main/java/com/homefit/backend/login/oauth/filter/TokenAuthenticationFilter.java
  src/main/java/com/homefit/backend/login/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/homefit/backend/login/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/homefit/backend/login/service/KakaoAuthService.java
  src/main/java/com/homefit/backend/user/controller/UserInfoController.java
  src/main/java/com/homefit/backend/user/dto/UserInfoDto.java
  src/main/java/com/homefit/backend/user/entity/UserInfo.java
  src/main/java/com/homefit/backend/user/service/UserInfoService.java
  src/main/resources/logback-spring.xml
  src/test/java/com/homefit/backend/login/service/LoginServiceTest.java
Labels: ⚙️ Setting

#45 [FEAT] 로그인/회원가입 로직 변경을 위한 기능 구현
  src/main/java/com/homefit/backend/BackendApplication.java
  src/main/java/com/homefit/backend/exerciselog/service/ExerciseLogService.java
  src/main/java/com/homefit/backend/global/util/OpenApiConfig.java
  src/main/java/com/homefit/backend/login/common/CookieUtil.java
  src/main/java/com/homefit/backend/login/common/HeaderUtil.java
  src/main/java/com/homefit/backend/login/config/AdminInitializer.java
  src/main/java/com/homefit/backend/login/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/homefit/backend/login/config/properties/AppProperties.java
  src/main/java/com/homefit/backend/login/config/provider/JwtTokenProvider.java
  src/main/java/com/homefit/backend/login/config/security/JwtConfig.java
  src/main/java/com/homefit/backend/login/config/security/SecurityConfig.java
  src/main/java/com/homefit/backend/login/controller/UserAuthController.java
  src/main/java/com/homefit/backend/login/controller/api/HomeController.java
  src/main/java/com/homefit/backend/login/controller/api/KakaoAuthController.java
  src/main/java/com/homefit/backend/login/dto/AdminDto.java
  src/main/java/com/homefit/backend/login/dto/KakaoLoginRequest.java
  src/main/java/com/homefit/backend/login/dto/LoginDto.java
  src/main/java/com/homefit/backend/login/dto/PasswordChangeDto.java
  src/main/java/com/homefit/backend/login/dto/UserDto.java
  src/main/java/com/homefit/backend/login/entity/RoleType.java
  src/main/java/com/homefit/backend/login/entity/User.java
  src/main/java/com/homefit/backend/login/entity/UserPrincipal.java
  src/main/java/com/homefit/backend/login/oauth/entity/ProviderType.java
  src/main/java/com/homefit/backend/login/oauth/entity/user/UserPrincipal.java
  src/main/java/com/homefit/backend/login/oauth/exception/RestAuthenticationEntryPoint.java
  src/main/java/com/homefit/backend/login/oauth/exception/TokenValidFailedException.java
  src/main/java/com/homefit/backend/login/oauth/filter/TokenAuthenticationFilter.java
  src/main/java/com/homefit/backend/login/oauth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/homefit/backend/login/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/homefit/backend/login/oauth/handler/TokenAccessDeniedHandler.java
  src/main/java/com/homefit/backend/login/oauth/info/OAuth2UserInfo.java
  src/main/java/com/homefit/backend/login/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/com/homefit/backend/login/oauth/info/impl/KakaoOAuth2UserInfo.java
  src/main/java/com/homefit/backend/login/oauth/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/homefit/backend/login/oauth/repository/UserRepository.java
  src/main/java/com/homefit/backend/login/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/homefit/backend/login/oauth/token/AuthToken.java
  src/main/java/com/homefit/backend/login/oauth/token/AuthTokenProvider.java
  src/main/java/com/homefit/backend/login/repository/UserRepository.java
  src/main/java/com/homefit/backend/login/service/AuthenticationService.java
  src/main/java/com/homefit/backend/login/service/CustomUserDetailsService.java
  src/main/java/com/homefit/backend/login/service/KakaoAuthService.java
  src/main/java/com/homefit/backend/login/service/UserService.java
  src/main/java/com/homefit/backend/login/util/CustomApiResponse.java
  src/test/java/com/homefit/backend/exerciselog/service/ExerciseLogServiceTest.java
  src/test/java/com/homefit/backend/login/service/LoginServiceTest.java
Labels: ✨ Feature

#49 Feat: 룸 생성, 제거 API 구현
  src/main/java/com/homefit/backend/room/controller/RoomController.java
  src/main/java/com/homefit/backend/room/dto/RoomCreateRequestDto.java
  src/main/java/com/homefit/backend/room/entity/Room.java
  src/main/java/com/homefit/backend/room/repository/RoomRepository.java
  src/main/java/com/homefit/backend/room/service/RoomService.java
Labels: ✨ Feature

#51 [FEAT] 사용자 로그인 성공 시 토큰 및 userId 추가 기능 구현
  src/main/java/com/homefit/backend/login/controller/UserAuthController.java
  src/main/java/com/homefit/backend/login/dto/LoginRequestDto.java
  src/main/java/com/homefit/backend/login/service/AuthenticationService.java
  src/test/java/com/homefit/backend/login/service/LoginServiceTest.java
Labels: ✨ Feature

#53 [FIX] 로그인 관련 클래스 추가
  src/main/java/com/homefit/backend/login/dto/LoginResponseDto.java
Labels: 🐞 Fix

#56 [FEAT] 로깅 전용 엔드포인트 추가 및 리팩토링
  src/main/java/com/homefit/backend/log/controller/LogController.java
  src/main/java/com/homefit/backend/log/service/LogManagementService.java
  src/main/java/com/homefit/backend/login/controller/UserAuthController.java
  src/main/java/com/homefit/backend/login/service/UserService.java
  src/main/java/com/homefit/backend/user/controller/UserInfoController.java
  src/main/java/com/homefit/backend/user/service/UserInfoService.java
Labels: ✨ Feature, 🔨 Refactor

#59 [FEAT] 캐릭터 매핑 관계 수정 및 유저 캐릭터 생성 구현
  src/main/java/com/homefit/backend/character/controller/CharacterController.java
  src/main/java/com/homefit/backend/character/entity/Character.java
  src/main/java/com/homefit/backend/character/repository/CharacterRepository.java
  src/main/java/com/homefit/backend/character/service/CharacterService.java
  src/main/java/com/homefit/backend/login/controller/UserAuthController.java
  src/main/java/com/homefit/backend/login/service/UserService.java
Labels: ✨ Feature

#63 [REFACTOR] 유저 캐릭터 생성 시 아이템 기본값 변경
  src/main/java/com/homefit/backend/character/service/CharacterService.java
Labels: 🔨 Refactor

#65 [REFACTOR] 유저 캐릭터 생성 시 아이템 기본값 재변경
  src/main/java/com/homefit/backend/character/service/CharacterService.java
Labels: 🔨 Refactor

#67 Feat/ranking
  build.gradle
  src/main/java/com/homefit/backend/ranking/config/RedisConfig.java
  src/main/java/com/homefit/backend/ranking/controller/RankingController.java
  src/main/java/com/homefit/backend/ranking/dto/RankingUpdateRequestDto.java
  src/main/java/com/homefit/backend/ranking/repository/RankingRepository.java
  src/main/java/com/homefit/backend/ranking/service/RankingService.java
  src/main/java/com/homefit/backend/ranking/util/RankingKeyUtil.java
  src/test/java/com/homefit/backend/ranking/service/RankingServiceTest.java
Labels: ✨ Feature

#70 Refactor: 유저 운동기록 전반적인 흐름 수정
  src/main/java/com/homefit/backend/exerciselog/controller/ExerciseLogController.java
  src/main/java/com/homefit/backend/exerciselog/dto/ExerciseLogRequest.java
  src/main/java/com/homefit/backend/exerciselog/dto/ExerciseLogResponse.java
  src/main/java/com/homefit/backend/exerciselog/entity/ExerciseLog.java
  src/main/java/com/homefit/backend/exerciselog/repository/ExerciseLogRepository.java
  src/main/java/com/homefit/backend/exerciselog/service/ExerciseLogService.java
  src/test/java/com/homefit/backend/exerciselog/service/ExerciseLogServiceTest.java
Labels: 🔨 Refactor

#72 room
  src/main/java/com/homefit/backend/room/controller/RoomController.java
  src/main/java/com/homefit/backend/room/entity/Room.java
  src/main/java/com/homefit/backend/room/repository/RoomRepository.java
  src/main/java/com/homefit/backend/room/service/RoomService.java
  src/test/java/com/homefit/backend/room/service/RoomServiceTest.java
Labels: 🐞 Fix, 🔨 Refactor

#78 [FIX] 로그인 도메인 버그 수정
  src/main/java/com/homefit/backend/login/config/AdminInitializer.java
  src/main/java/com/homefit/backend/login/service/AuthService.java
Labels: 🐞 Fix

#81 [REFACTOR] 자잘한 코드 리팩토링
  src/main/java/com/homefit/backend/character/controller/CharacterController.java
  src/main/java/com/homefit/backend/character/dto/CharacterUpdateRequestDto.java
  src/main/java/com/homefit/backend/log/controller/LogController.java
  src/main/java/com/homefit/backend/log/service/LogManagementService.java
  src/main/java/com/homefit/backend/user/controller/UserInfoController.java
  src/main/java/com/homefit/backend/user/service/UserInfoService.java
  src/main/resources/logback-spring.xml
Labels: 🔨 Refactor
